### ISSUE TITLE
Kafka cluster state and kafka cluster admin page is not loading.

### ISSUE THREAD

**Issue by ananthdurai** [linkedin/cruise-control-ui#14]
I'm getting the following exception whenever trying to open the cluster state and the admin page.
The error happens only on a slightly larger Kafka cluster (30+ nodes)

<img width="900" alt="Screenshot 2019-03-14 13 26 02" src="https://user-images.githubusercontent.com/12244730/54389271-ee45d400-465c-11e9-9779-651493580083.png">

is there any workaround to fix it?

The git commit hash I deployed: cf37ebf178347548c6c6a4fa234c7880c5bbbd9a

**Comment by nareshv** [comment]
which version of kafka & cruise-control are you running ?

**Comment by ananthdurai** [comment]
cruise control commit hash: 2833695fc1c978b8427ef388af8c00eb39cc78ef
and Kafka version 2.0.1

**Comment by nareshv** [comment]
i see some change to the `async operation response` from CC.. Lemme try to reproduce this on my side.

**Comment by nareshv** [comment]
It looks like the server is not sending any response in this context. can you confirm you are able to get valid  JSON response for `/kafkacruisecontrol/kafka_cluster_state?json=true` from your CC ?

Also, how much time is it taking for you to get the above response in this case ?

**Comment by ananthdurai** [comment]
It is the cruise control API error indeed. I got the following stack trace in cc.

2019-03-16_15:11:27.00772 [2019-03-16 08:11:27,007] ERROR Failed to populate broker logDir state. (com.linkedin.kafka.cruisecontrol.servlet.response.KafkaClusterState)
2019-03-16_15:11:27.00785 java.util.concurrent.TimeoutException
2019-03-16_15:11:27.00794 	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:108)
2019-03-16_15:11:27.00869 	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:274)
2019-03-16_15:11:27.00884 	at com.linkedin.kafka.cruisecontrol.servlet.response.KafkaClusterState.populateKafkaBrokerLogDirState(KafkaClusterState.java:308)
2019-03-16_15:11:27.00903 	at com.linkedin.kafka.cruisecontrol.servlet.response.KafkaClusterState.getJsonStructure(KafkaClusterState.java:241)
2019-03-16_15:11:27.00922 	at com.linkedin.kafka.cruisecontrol.servlet.response.KafkaClusterState.getJSONString(KafkaClusterState.java:84)
2019-03-16_15:11:27.00941 	at com.linkedin.kafka.cruisecontrol.servlet.response.KafkaClusterState.discardIrrelevantAndCacheRelevant(KafkaClusterState.java:428)
2019-03-16_15:11:27.00963 	at com.linkedin.kafka.cruisecontrol.servlet.response.AbstractCruiseControlResponse.discardIrrelevantResponse(AbstractCruiseControlResponse.java:40)
2019-03-16_15:11:27.00977 	at com.linkedin.kafka.cruisecontrol.servlet.response.AbstractCruiseControlResponse.writeSuccessResponse(AbstractCruiseControlResponse.java:31)
2019-03-16_15:11:27.01002 	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.getKafkaClusterState(KafkaCruiseControlServlet.java:418)
2019-03-16_15:11:27.01014 	at com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet.doGet(KafkaCruiseControlServlet.java:193)
2019-03-16_15:11:27.01043 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
2019-03-16_15:11:27.01044 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
2019-03-16_15:11:27.01046 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
2019-03-16_15:11:27.01047 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
2019-03-16_15:11:27.01047 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
2019-03-16_15:11:27.01073 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
2019-03-16_15:11:27.01088 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
2019-03-16_15:11:27.01090 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
2019-03-16_15:11:27.01090 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
2019-03-16_15:11:27.01103 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
2019-03-16_15:11:27.01105 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
2019-03-16_15:11:27.01106 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
2019-03-16_15:11:27.01106 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
2019-03-16_15:11:27.01107 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
2019-03-16_15:11:27.01107 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
2019-03-16_15:11:27.01132 	at org.eclipse.jetty.server.Server.handle(Server.java:564)
2019-03-16_15:11:27.01134 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
2019-03-16_15:11:27.01135 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
2019-03-16_15:11:27.01135 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
2019-03-16_15:11:27.01136 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
2019-03-16_15:11:27.01136 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
2019-03-16_15:11:27.01151 	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
2019-03-16_15:11:27.01156 	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
2019-03-16_15:11:27.01171 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
2019-03-16_15:11:27.01171 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
2019-03-16_15:11:27.01172 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
2019-03-16_15:11:27.01172 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
2019-03-16_15:11:27.01190 	at java.lang.Thread.run(Thread.java:748)

**Comment by nareshv** [comment]
created a ticket with CC

**Comment by nareshv** [comment]
@ananthdurai , pushed code to `v0.3.0` branch to support handling empty responses from CC. Please, let me know if it works for you now.

```
git clone https://github.com/linkedin/cruise-control-ui
git checkout v0.3.0
npm install && npm run build
```

deploy the contents of `build/*`

**Comment by nareshv** [comment]
please create a new issue if something similar occurs again.
