### ISSUE TITLE
Running locally - Issue

### ISSUE THREAD

**Issue by chetann** [linkedin/cruise-control-ui#33]
I am getting the below issue while running CC-UI locally. Can someone kindly help me out.
```Refused to load the image 'http://0.0.0.0:8090/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.```

**Comment by linc01n** [comment]
is it showing `Cannot GET /` ?

**Comment by chetann** [comment]
Yes

**Comment by mars76** [comment]
I am getting the same error as well. ( when i go to http;//0.0.0.0:8090 and http://localhost:9090 is returning site can't be reached. There is nothing running on port 9090 using netstat)

Where is the config related to which kafka cluster (kafka Brokers , zookepper etc) it is pointing to ? Is that configured once the UI is up ?

**Comment by linc01n** [comment]
The above MR should fix this. It is not about the config. `src/components/Executor.vue` got error.

**Comment by chetann** [comment]
I did update the Executor.vue @linc01n but still when I do `npm run dev` still ending up with 
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                      10:00:16 AM

Module build failed: Error: No ESLint configuration found.
    at getLocalConfig (/Users/z076952/Documents/Data_movement_git/tgtcruisecontrol-UI/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/Users/z076952/Documents/Data_movement_git/tgtcruisecontrol-UI/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/z076952/Documents/Data_movement_git/tgtcruisecontrol-UI/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/z076952/Documents/Data_movement_git/tgtcruisecontrol-UI/node_modules/eslint/lib/cli-engine.js:754:26)
    at lint (/Users/z076952/Documents/Data_movement_git/tgtcruisecontrol-UI/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/Users/z076952/Documents/Data_movement_git/tgtcruisecontrol-UI/node_modules/eslint-loader/index.js:213:21)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
> Listening at http://0.0.0.0:8090
```
Can you kindly help me out. Did even try to remove the ESlint packages but it did not help me out.

**Comment by linc01n** [comment]
@chetann You should able to run `npm run dev` with this file `.eslintrc.js` in the repo. Do you have this file in your project directory?
